services:
  mysql:
    image: mysql:9.5.0
    container_name: ecommerce_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 53cret
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: yu71
      MYSQL_PASSWORD: 53cret
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
